INSERT INTO RespuestaOtis_Aspirante (Id_respuestaOtis, Id_aspirante, Id_pruebaOtis, Id_preguntaOtis, Id_opcionPreguntaOtis, Respuesta_abierta, Tiempo_respuesta) 
VALUES
(UUID(), (SELECT Id_aspirante FROM Aspirantes WHERE Id_aspirante = (SELECT Id_aspirante FROM Aspirantes WHERE Id_usuario = (SELECT Id_usuario FROM Usuarios WHERE Correo = 'juanlópez39@example.com'))), (SELECT Id_pruebaOtis FROM PruebaOtis WHERE Id_prueba = (SELECT Id_prueba FROM Pruebas WHERE Nombre = 'OTIS')), (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 1), (SELECT Id_opcionPreguntaOtis FROM OpcionesPreguntasOtis WHERE Id_preguntaOtis = (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 1) AND Numero_opcion = 1), NULL, 15),
(UUID(), (SELECT Id_aspirante FROM Aspirantes WHERE Id_aspirante = (SELECT Id_aspirante FROM Aspirantes WHERE Id_usuario = (SELECT Id_usuario FROM Usuarios WHERE Correo = 'maríapérez76@example.com'))), (SELECT Id_pruebaOtis FROM PruebaOtis WHERE Id_prueba = (SELECT Id_prueba FROM Pruebas WHERE Nombre = 'OTIS')), (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 2), NULL, 'Perro', 20),
(UUID(), (SELECT Id_aspirante FROM Aspirantes WHERE Id_aspirante = (SELECT Id_aspirante FROM Aspirantes WHERE Id_usuario = (SELECT Id_usuario FROM Usuarios WHERE Correo = 'carlosrodríguez58@example.com'))), (SELECT Id_pruebaOtis FROM PruebaOtis WHERE Id_prueba = (SELECT Id_prueba FROM Pruebas WHERE Nombre = 'OTIS')), (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 3), (SELECT Id_opcionPreguntaOtis FROM OpcionesPreguntasOtis WHERE Id_preguntaOtis = (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 3) AND Numero_opcion = 1), NULL, 30),
(UUID(), (SELECT Id_aspirante FROM Aspirantes WHERE Id_aspirante = (SELECT Id_aspirante FROM Aspirantes WHERE Id_usuario = (SELECT Id_usuario FROM Usuarios WHERE Correo = 'lauragómez50@example.com'))), (SELECT Id_pruebaOtis FROM PruebaOtis WHERE Id_prueba = (SELECT Id_prueba FROM Pruebas WHERE Nombre = 'OTIS')), (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 4), (SELECT Id_opcionPreguntaOtis FROM OpcionesPreguntasOtis WHERE Id_preguntaOtis = (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 4) AND Numero_opcion = 1), NULL, 12),
(UUID(), (SELECT Id_aspirante FROM Aspirantes WHERE Id_aspirante = (SELECT Id_aspirante FROM Aspirantes WHERE Id_usuario = (SELECT Id_usuario FROM Usuarios WHERE Correo = 'pedrofernández59@example.com'))), (SELECT Id_pruebaOtis FROM PruebaOtis WHERE Id_prueba = (SELECT Id_prueba FROM Pruebas WHERE Nombre = 'OTIS')), (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 5), NULL, 'Juan', 25),
(UUID(), (SELECT Id_aspirante FROM Aspirantes WHERE Id_aspirante = (SELECT Id_aspirante FROM Aspirantes WHERE Id_usuario = (SELECT Id_usuario FROM Usuarios WHERE Correo = 'anamartínez97@example.com'))), (SELECT Id_pruebaOtis FROM PruebaOtis WHERE Id_prueba = (SELECT Id_prueba FROM Pruebas WHERE Nombre = 'OTIS')), (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 6), (SELECT Id_opcionPreguntaOtis FROM OpcionesPreguntasOtis WHERE Id_preguntaOtis = (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 6) AND Numero_opcion = 1), NULL, 18),
(UUID(), (SELECT Id_aspirante FROM Aspirantes WHERE Id_aspirante = (SELECT Id_aspirante FROM Aspirantes WHERE Id_usuario = (SELECT Id_usuario FROM Usuarios WHERE Correo = 'luisramírez75@example.com'))), (SELECT Id_pruebaOtis FROM PruebaOtis WHERE Id_prueba = (SELECT Id_prueba FROM Pruebas WHERE Nombre = 'OTIS')), (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 7), (SELECT Id_opcionPreguntaOtis FROM OpcionesPreguntasOtis WHERE Id_preguntaOtis = (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 7) AND Numero_opcion = 1), NULL, 10),
(UUID(), (SELECT Id_aspirante FROM Aspirantes WHERE Id_aspirante = (SELECT Id_aspirante FROM Aspirantes WHERE Id_usuario = (SELECT Id_usuario FROM Usuarios WHERE Correo = 'sofíaramírez88@example.com'))), (SELECT Id_pruebaOtis FROM PruebaOtis WHERE Id_prueba = (SELECT Id_prueba FROM Pruebas WHERE Nombre = 'OTIS')), (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 8), (SELECT Id_opcionPreguntaOtis FROM OpcionesPreguntasOtis WHERE Id_preguntaOtis = (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 8) AND Numero_opcion = 1), NULL, 22),
(UUID(), (SELECT Id_aspirante FROM Aspirantes WHERE Id_aspirante = (SELECT Id_aspirante FROM Aspirantes WHERE Id_usuario = (SELECT Id_usuario FROM Usuarios WHERE Correo = 'miguelramírez66@example.com'))), (SELECT Id_pruebaOtis FROM PruebaOtis WHERE Id_prueba = (SELECT Id_prueba FROM Pruebas WHERE Nombre = 'OTIS')), (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 9), NULL, '6:00', 14),
(UUID(), (SELECT Id_aspirante FROM Aspirantes WHERE Id_aspirante = (SELECT Id_aspirante FROM Aspirantes WHERE Id_usuario = (SELECT Id_usuario FROM Usuarios WHERE Correo = 'elenagarcía10@example.com'))), (SELECT Id_pruebaOtis FROM PruebaOtis WHERE Id_prueba = (SELECT Id_prueba FROM Pruebas WHERE Nombre = 'OTIS')), (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 10), (SELECT Id_opcionPreguntaOtis FROM OpcionesPreguntasOtis WHERE Id_preguntaOtis = (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 10) AND Numero_opcion = 1), NULL, 19),
(UUID(), (SELECT Id_aspirante FROM Aspirantes WHERE Id_aspirante = (SELECT Id_aspirante FROM Aspirantes WHERE Id_usuario = (SELECT Id_usuario FROM Usuarios WHERE Correo = 'javierfernández98@example.com'))), (SELECT Id_pruebaOtis FROM PruebaOtis WHERE Id_prueba = (SELECT Id_prueba FROM Pruebas WHERE Nombre = 'OTIS')), (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 11), (SELECT Id_opcionPreguntaOtis FROM OpcionesPreguntasOtis WHERE Id_preguntaOtis = (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 11) AND Numero_opcion = 1), NULL, 30),
(UUID(), (SELECT Id_aspirante FROM Aspirantes WHERE Id_aspirante = (SELECT Id_aspirante FROM Aspirantes WHERE Id_usuario = (SELECT Id_usuario FROM Usuarios WHERE Correo = 'lucíaramírez83@example.com'))), (SELECT Id_pruebaOtis FROM PruebaOtis WHERE Id_prueba = (SELECT Id_prueba FROM Pruebas WHERE Nombre = 'OTIS')), (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 12), (SELECT Id_opcionPreguntaOtis FROM OpcionesPreguntasOtis WHERE Id_preguntaOtis = (SELECT Id_preguntaOtis FROM PreguntasOtis WHERE Numero_pregunta = 12) AND Numero_opcion = 1), NULL, 20);