INSERT INTO estados (idEstado, nombreEstado) VALUES
(UUID(), 'Aguascalientes'),
(UUID(), 'Baja California'),
(UUID(), 'Baja California Sur'),
(UUID(), 'Campeche'),
(UUID(), 'Chiapas'),
(UUID(), 'Chihuahua'),
(UUID(), 'Coahuila'),
(UUID(), 'Colima'),
(UUID(), 'Durango'),
(UUID(), 'Guanajuato'),
(UUID(), 'Guerrero'),
(UUID(), 'Hidalgo'),
(UUID(), 'Jalisco'),
(UUID(), 'Estado de México'),
(UUID(), 'Michoacán'),
(UUID(), 'Morelos'),
(UUID(), 'Nayarit'),
(UUID(), 'Nuevo León'),
(UUID(), 'Oaxaca'),
(UUID(), 'Puebla'),
(UUID(), 'Querétaro'),
(UUID(), 'Quintana Roo'),
(UUID(), 'San Luis Potosí'),
(UUID(), 'Sinaloa'),
(UUID(), 'Sonora'),
(UUID(), 'Tabasco'),
(UUID(), 'Tamaulipas'),
(UUID(), 'Tlaxcala'),
(UUID(), 'Veracruz'),
(UUID(), 'Yucatán'),
(UUID(), 'Zacatecas'),
(UUID(), 'Ciudad de México');