INSERT INTO respuestaOtisAspirante (idRespuestaOtis, idAspirante, idPruebaOtis, idPreguntaOtis, idOpcionPreguntaOtis, respuestaAbierta, tiempoRespuesta) 
VALUES
(UUID(), (SELECT idAspirante FROM aspirantes WHERE idAspirante = (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'juanlópez39@example.com'))), (SELECT idPruebaOtis FROM pruebaOtis WHERE idPrueba = (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS')), (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 1), (SELECT idOpcionPreguntaOtis FROM opcionesPreguntasOtis WHERE idPreguntaOtis = (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 1) AND numeroOpcion = 1), NULL, 15),
(UUID(), (SELECT idAspirante FROM aspirantes WHERE idAspirante = (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'maríapérez76@example.com'))), (SELECT idPruebaOtis FROM pruebaOtis WHERE idPrueba = (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS')), (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 2), NULL, 'Perro', 20),
(UUID(), (SELECT idAspirante FROM aspirantes WHERE idAspirante = (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'carlosrodríguez58@example.com'))), (SELECT idPruebaOtis FROM pruebaOtis WHERE idPrueba = (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS')), (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 3), (SELECT idOpcionPreguntaOtis FROM opcionesPreguntasOtis WHERE idPreguntaOtis = (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 3) AND numeroOpcion = 1), NULL, 30),
(UUID(), (SELECT idAspirante FROM aspirantes WHERE idAspirante = (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'lauragómez50@example.com'))), (SELECT idPruebaOtis FROM pruebaOtis WHERE idPrueba = (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS')), (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 4), (SELECT idOpcionPreguntaOtis FROM opcionesPreguntasOtis WHERE idPreguntaOtis = (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 4) AND numeroOpcion = 1), NULL, 12),
(UUID(), (SELECT idAspirante FROM aspirantes WHERE idAspirante = (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'pedrofernández59@example.com'))), (SELECT idPruebaOtis FROM pruebaOtis WHERE idPrueba = (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS')), (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 5), NULL, 'Juan', 25),
(UUID(), (SELECT idAspirante FROM aspirantes WHERE idAspirante = (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'anamartínez97@example.com'))), (SELECT idPruebaOtis FROM pruebaOtis WHERE idPrueba = (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS')), (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 6), (SELECT idOpcionPreguntaOtis FROM opcionesPreguntasOtis WHERE idPreguntaOtis = (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 6) AND numeroOpcion = 1), NULL, 18),
(UUID(), (SELECT idAspirante FROM aspirantes WHERE idAspirante = (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'luisramírez75@example.com'))), (SELECT idPruebaOtis FROM pruebaOtis WHERE idPrueba = (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS')), (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 7), (SELECT idOpcionPreguntaOtis FROM opcionesPreguntasOtis WHERE idPreguntaOtis = (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 7) AND numeroOpcion = 1), NULL, 10),
(UUID(), (SELECT idAspirante FROM aspirantes WHERE idAspirante = (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'sofíaramírez88@example.com'))), (SELECT idPruebaOtis FROM pruebaOtis WHERE idPrueba = (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS')), (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 8), (SELECT idOpcionPreguntaOtis FROM opcionesPreguntasOtis WHERE idPreguntaOtis = (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 8) AND numeroOpcion = 1), NULL, 22),
(UUID(), (SELECT idAspirante FROM aspirantes WHERE idAspirante = (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'miguelramírez66@example.com'))), (SELECT idPruebaOtis FROM pruebaOtis WHERE idPrueba = (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS')), (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 9), NULL, '6:00', 14),
(UUID(), (SELECT idAspirante FROM aspirantes WHERE idAspirante = (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'elenagarcía10@example.com'))), (SELECT idPruebaOtis FROM pruebaOtis WHERE idPrueba = (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS')), (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 10), (SELECT idOpcionPreguntaOtis FROM opcionesPreguntasOtis WHERE idPreguntaOtis = (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 10) AND numeroOpcion = 1), NULL, 19),
(UUID(), (SELECT idAspirante FROM aspirantes WHERE idAspirante = (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'javierfernández98@example.com'))), (SELECT idPruebaOtis FROM pruebaOtis WHERE idPrueba = (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS')), (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 11), (SELECT idOpcionPreguntaOtis FROM opcionesPreguntasOtis WHERE idPreguntaOtis = (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 11) AND numeroOpcion = 1), NULL, 30),
(UUID(), (SELECT idAspirante FROM aspirantes WHERE idAspirante = (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'lucíaramírez83@example.com'))), (SELECT idPruebaOtis FROM pruebaOtis WHERE idPrueba = (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS')), (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 12), (SELECT idOpcionPreguntaOtis FROM opcionesPreguntasOtis WHERE idPreguntaOtis = (SELECT idPreguntaOtis FROM preguntasOtis WHERE numeroPregunta = 12) AND numeroOpcion = 1), NULL, 20);
