INSERT INTO preguntasotis (idPreguntaOtis, idPrueba, numeroPregunta, preguntaOtis, idAreaOtis) VALUES
(UUID(), 5, 1, '¿Qué expresa mejor lo que es un martillo?', 1),
(UUID(), 5, 2, '¿Cuál de estas cinco palabras significa lo contrario de GANAR?', 1),
(UUID(), 5, 3, 'La hierba es para la vaca lo que el pan es para…', 2),
(UUID(), 5, 4, '¿Qué es para el automóvil lo que el carbón es para la locomotora?', 2),
(UUID(), 5, 5, 'Los números que vienen aquí debajo forman una serie y uno de ellos no es correcto. ¿Qué número debería figurar en su lugar?            5  10  15  20  25  30  35  39  45  50', 5),
(UUID(), 5, 6, 'La mano es para el brazo lo que el pie es para…', 2),
(UUID(), 5, 7, 'De un muchacho que no hace más que hablar de sus cualidades y de su sabiduría, se dice que…', 1),
(UUID(), 5, 8, 'De una persona que tiene deseos de hacer una cosa pero teme al fracaso, se dice que es…', 1),
(UUID(), 5, 9, 'El sombrero es para la cabeza lo que el dedal es para…', 2),
(UUID(), 5, 10, 'El hijo de la hermana de mi padre es mi…', 2),
(UUID(), 5, 11, '¿Cuál de estas cantidades es la mayor?', 5),
(UUID(), 5, 12, 'Cuando sabemos que un acontecimiento va a pasar sin ninguna clase de dudas, decimos que es…', 1),
(UUID(), 5, 13, '¿Qué palabra indica el lado opuesto de ESTE?', 1),
(UUID(), 5, 14, '¿Qué palabra indica lo contrario a SOBERBIA? ', 1),
(UUID(), 5, 15, '¿Cuál de estas cinco cosas no debería agruparse a las demás?', 2),
(UUID(), 5, 16, '¿Qué definición de éstas expresa más exactamente lo que es un reloj?', 4),
(UUID(), 5, 17, 'Si una persona, al salir de su casa, anda siete pasos hacia la derecha y después retrocede cuatro a la izquierda, ¿A cuantos pasos está de su casa? ', 5),
(UUID(), 5, 18, 'Si comparamos el automóvil a una carreta, ¿A qué deberíamos comparar una motocicleta?', 2),
(UUID(), 5, 19, '¿Cuál es la razón por la cuál las fachadas de los comercios están muy iluminadas?', 4),
(UUID(), 5, 20, '¿Cuál de estas cinco cosas tiene más parecido con manzana, melocotón y pera?', 1),
(UUID(), 5, 21, 'En el abecedario, ¿Qué letra sigue de la K?', 3),
(UUID(), 5, 22, 'El Rey es a la monarquía lo que el Presidente es a…', 2),
(UUID(), 5, 23, 'La lana es para el carnero lo que las plumas son para…', 2),
(UUID(), 5, 24, '¿Cuál de estas definiciones expresa más exactamente lo que es un cordero?', 4),
(UUID(), 5, 25, 'Pesado es a plomo lo que sonoro es a…', 2),
(UUID(), 5, 26, 'Mejor es a bueno lo que peor es a…', 2),
(UUID(), 5, 27, '¿Cuál de estas cosas tiene más parecido con tenazas, alambre y clavo?', 1),
(UUID(), 5, 28, 'Ante el dolor de los demás normalmente sentimos…', 1),
(UUID(), 5, 29, 'Cuando alguien concibe una nueva máquina, se dice que ha hecho una…', 1),
(UUID(), 5, 30, '¿Qué es para la abeja lo que las uñas son para el gato?', 2),
(UUID(), 5, 31, 'Uno de los números de esta serie está equivocado. ¿Qué número debería figurar en su lugar?                    1  7  2  7  3  7  4  7  5  7  6  7  8  7', 5),
(UUID(), 5, 32, '¿Cuál es la principal razón por la que vemos cada día sustituir los carros por los automóviles?', 4),
(UUID(), 5, 33, 'La corteza es para la naranja y la vaina es para el guisante lo que la cáscara es para…', 2),
(UUID(), 5, 34, '¿Qué es para el criminal lo que el hospital es para el enfermo?', 2),
(UUID(), 5, 35, 'Si estos números estuviesen ordenados, ¿Por qué letra empezaría el del centro?      Ocho  Diez   Seis   Nueve   Siete', 3),
(UUID(), 5, 36, 'A 30 centavos la hoja de papel, ¿Cuántas podrán comprarse por 3 pesos?', 5),
(UUID(), 5, 37, 'De una cantidad que disminuye se dice que…', 1),
(UUID(), 5, 38, 'Hay un refrán que dice "No es oro todo lo que reluce" y esto significa:', 4),
(UUID(), 5, 39, 'En una lengua extranjera KOLO quiere decir "niño" y DAAK KOLO "niño bueno", ¿Por qué letra empieza la palabra que significa "bueno" en ese idioma?', 3),
(UUID(), 5, 40, 'Este refrán, "Más vale pájaro en mano que ciento volando", quiere decir:', 4),
(UUID(), 5, 41, '¿Cuál de estas cinco cosas es más completa?', 1),
(UUID(), 5, 42, 'Si estas palabras estuviesen convenientemente ordenadas para formar una frase, ¿Por qué letra empezaría la tercera palabra?      CON  DIME  ERES  QUIEN  DIRE  ANDAS  Y  TE  QUIEN', 3),
(UUID(), 5, 43, 'Si Jorge es mayor que Pedro, y Pedro es mayor que Juan, entonces Jorge es ______ que Juan.', 2),
(UUID(), 5, 44, '¿Cuál de estas palabras es la primera que aparece en el diccionario?', 3),
(UUID(), 5, 45, 'Si las palabras General, Teniente, Soldado, Coronel y Alférez estuviesen colocadas indicando el orden jerárquico que significan, ¿Por qué letra empezaría la del centro?             (Alférez: Oficial de categoría menor al teniente)', 3),
(UUID(), 5, 46, 'Hay un refrán que dice: "Un grano no hace granero, pero ayuda al compañero", y esto significa:', 4),
(UUID(), 5, 47, 'Si Juan es mayor que José, y José tiene la misma edad que Carlos entonces…', 2),
(UUID(), 5, 48, 'Ordenando la frase que viene aquí debajo, ¿Por qué letra empezaría la última palabra?     A  FALTA  TORTAS  BUENAS  PAN  SON  DE', 3),
(UUID(), 5, 49, 'Si en una caja hubiera dos más pequeñas y dentro de cada una de estas dos hubiera cinco, ¿Cuántas habría en total?', 5),
(UUID(), 5, 50, '¿Qué indica mejor lo que es una mentira?', 4),
(UUID(), 5, 51, 'En un idioma extranjero SOTO GRON quiere decir "muy caliente" y PSS GRON "muy frío", ¿Por qué letra empieza la palabra que significa "muy" en ese idioma?', 3),
(UUID(), 5, 52, 'La palabra que mejor expresa que una cosa o institución se mantiene a lo largo del tiempo es…', 1),
(UUID(), 5, 53, 'Si Pablo es mayor que Luis y si Pablo es más joven que Andrés, entonces…', 2),
(UUID(), 5, 54, '¿Cuál de estas cosas tiene más parecido con serpiente, vaca y gorrión?', 1),
(UUID(), 5, 55, 'Hay un refrán que dice: "A hierro caliente, batir de repente", y esto significa:', 4),
(UUID(), 5, 56, 'Si las palabras que vienen aquí debajo estuviesen ordenadas, ¿Por qué letra empezaría la del centro?        Semana  Año  Hora  Segundo  Día  Mes  Minuto', 3),
(UUID(), 5, 57, ' El capitán es para el barco lo que el alcalde es para…', 2),
(UUID(), 5, 58, 'Uno de los números de la serie que viene aquí debajo está equivocado, ¿Qué número debiera figurar en su lugar?       2  3  4  3  2  3  4  2  2  4', 5),
(UUID(), 5, 59, 'Si un pleito se resuelve por mutuas concesiones se dice que ha habido…', 1),
(UUID(), 5, 60, 'La oración que viene aquí debajo tiene las palabras desordenadas. ¿Qué letra debe marcarse atendiendo a la frase ordenada?       	FRASE  LA  LETRA  SEÑALE  PRIMERA  ESTA  DE', 3),
(UUID(), 5, 61, 'En la serie de números, que aparece debajo, cuente todos los 5 que están delante de un 7, ¿Cuántos son?    7 5 3 5 7 2 3 7 5 6 7 7 2 5 7 3 4 7 7 5 2 0 7 5 7 8 3 7 2 5 1 7 9 6 5 7', 3),
(UUID(), 5, 62, '¿Qué indica mejor lo que es un termómetro?', 4),
(UUID(), 5, 63, '¿Cuál de estas palabras es la primera que aparece en un diccionario?', 3),
(UUID(), 5, 64, 'Uno de los números de la serie que aparece aquí debajo está equivocado. ¿Qué número debiera figurar en su lugar?    1  2  4  8  12  32  64', 5),
(UUID(), 5, 65, '¿Cuál de estas palabras significa lo contrario de COMUN?', 1),
(UUID(), 5, 66, '¿Cuál de estas cinco cosas tiene más parecido con Presidente, Almirante y General?', 1),
(UUID(), 5, 67, 'Si las palabras que aparecen aquí debajo estuvieran ordenadas, ¿Por qué letra empezaría la del centro?     Adolescente  Niño  Hombre  Viejo  Bebé', 3),
(UUID(), 5, 68, '¿Cuál de estas definiciones indica más exactamente lo que es un caballo?', 4),
(UUID(), 5, 69, 'En un idioma extranjero BECO PRAC quiere decir "un poco de pan", KLUP PRAC "un poco de leche" y BECO OTOH KLUP PRAC "un poco de pan y leche", ¿Por qué letra empieza la palabra que significa "y" en dicho idioma?', 3),
(UUID(), 5, 70, 'Si las palabras que aparecen aquí debajo estuviesen convenientemente ordenadas para formar una frase, ¿Por qué letra empezaría la tercera palabra?     MADRUGA  QUIEN   LE  DIOS  A  AYUDA', 3),
(UUID(), 5, 71, '¿Cuál de estas palabras es la última que aparece en un diccionario?', 3),
(UUID(), 5, 72, 'Si se ordena la frase que aparece aquí debajo, ¿Qué letra cumple lo que se dice en ella?', 3),
(UUID(), 5, 73, 'Uno de los números de la serie que aparece aquí debajo está equivocado, ¿Qué número debería figurar en su lugar?         1  2  5  6  9  10  13  14  16  18', 5),
(UUID(), 5, 74, 'Si un ciclista recorre 250 metros en 25 segundos, ¿Cuántos metros recorrerá en un quinto de segundo?', 5),
(UUID(), 5, 75, 'Si la frase que aparece aquí debajo estuviera ordenada, ¿Qué número cumple lo que en ella se dice?        SUMA  CUATRO  ESCRIBA  TRES  LA  UNO  DE', 3);
