INSERT INTO preguntasOtis (idPreguntaOtis, idPrueba, numeroPregunta, pregunta)
VALUES
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 1, '¿Cuál de estas cinco palabras indica mejor lo que es una manzana?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 2, '¿Cuál de estas cinco palabras indica mejor lo que es un círculo?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 3, 'Si reordenamos las letras "ROFMA", ¿qué palabra se forma?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 4, 'Si reordenamos las letras "GATO", ¿qué palabra se forma?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 5, '¿Cuál de estas cinco cosas no pertenece al mismo grupo?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 6, '¿Qué número sigue en esta serie: 4, 8, 12, 16, 20, ...?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 7, 'Si el día después de mañana es domingo, ¿qué día fue ayer?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 8, 'Un comerciante compró algunos artículos por 27 pesos y los vendió por 30 pesos. ¿Cuánto ganó?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 9, 'Si 3 hombres pueden hacer un trabajo en 7 días, ¿cuántos hombres se necesitan para hacerlo en 1 día?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 10, 'Si dos pasteles cuestan 30 centavos, ¿cuántos pasteles se pueden comprar con 90 centavos?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 11, '¿Cuál de estos cinco números no pertenece al mismo grupo? 2, 4, 8, 12, 16'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 12, 'Si un tren viaja a 60 kilómetros por hora, ¿cuánto tiempo tardará en recorrer 300 kilómetros?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 13, 'Si una persona tiene 14 años y su hermano tiene el doble de edad, ¿cuántos años tendrá el hermano cuando la persona tenga 40 años?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 14, 'En una carrera, si adelantas al segundo, ¿en qué posición terminarás?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 15, 'Si 7 hombres construyen 6 casas en 3 días, ¿cuántas casas construirán 21 hombres en 7 días?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 16, 'Si uno dice "Un hombre puede hacer un trabajo en 4 días" y otro dice "Cuatro hombres pueden hacer el trabajo en 1 día", ¿quién tiene razón?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 17, 'Si un objeto cae 16 pies en el primer segundo, 48 pies en los dos primeros segundos, y 80 pies en los tres primeros segundos, ¿cuántos pies caerá en el cuarto segundo?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 18, 'Completa la analogía: Pájaro es a aire como pez es a...'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 19, 'Si Juan tiene 5 naranjas y Pedro tiene 8 naranjas, ¿cuántas naranjas debe dar Pedro a Juan para que ambos tengan la misma cantidad?'),
(UUID(), (SELECT idPrueba FROM pruebas WHERE nombre = 'OTIS'), 20, 'Si X es mayor que Y, y Y es mayor que Z, entonces X es __ que Z.');