INSERT INTO PreguntasFormatoEntrevista VALUES 
(UUID(), 'Nombre'),
(UUID(), 'Fecha de Nacimiento'),
(UUID(), 'Edad (Años cumplidos)'),
(UUID(), 'Género'),
(UUID(), 'Estado Civil'),
(UUID(), 'Nacionalidad'),
(UUID(), 'Originario de'),
(UUID(), 'Dirección Actual'),
(UUID(), 'Teléfono(s)'),
(UUID(), 'Celular'),
(UUID(), 'Correo'),
(UUID(), 'Realice una descripción amplia de su persona'),
(UUID(), 'Describa su estado de ánimo cotidiano'),
(UUID(), 'Describa su estado de ánimo en situaciones de presión'),
(UUID(), 'Describa su estado de ánimo en situaciones críticas'),
(UUID(), '¿Cómo considera que es su estado de salud?'),
(UUID(), '¿A qué dedica sus tiempos libres?'),
(UUID(), 'Nombre de la Licenciatura'),
(UUID(), 'Institución de Procedencia'),
(UUID(), 'Promedio de egreso'),
(UUID(), 'Generación'),
(UUID(), 'Grado máximo de estudios'),
(UUID(), 'Maestría o especialidad (en caso de tener)'),
(UUID(), 'Institución donde cursó la Maestría'),
(UUID(), 'Promedio de egreso de la Maestría'),
(UUID(), 'Cursos y Diplomados (Escribir los de los últimos tres años)'),
(UUID(), 'Idiomas que domina'),
(UUID(), '¿Cómo considera que ha sido su desempeño académico hasta llegar a este posgrado?'),
(UUID(), '¿Cuáles han sido los cursos de actualización, los seminarios o congresos a los que ha asistido que le han brindado mayores herramientas en su desarrollo profesional o personal?'),
(UUID(), '¿Cómo surge el interés en este programa de posgrado?'),
(UUID(), '¿Cuál es la finalidad de estudiar este posgrado y cómo se integrará en sus experiencias personales y/o profesionales?'),
(UUID(), '¿Cuáles son sus expectativas acerca de las aportaciones que le pueda hacer este posgrado?'),
(UUID(), 'Explique su visión respecto a su desarrollo profesional en años posteriores a su egreso de este posgrado'),
(UUID(), '¿Está dispuesto a cambiar de residencia?'),
(UUID(), 'Datos Laborales (escribe el último trabajo en el que te desempeñaste)'),
(UUID(), 'Lugar donde trabaja'),
(UUID(), 'Nombre de la empresa'),
(UUID(), 'Puesto que desempeña'),
(UUID(), 'Años en la empresa'),
(UUID(), 'Actividades que realiza'),
(UUID(), 'Sueldo que percibe'),
(UUID(), '¿Tiene personal a su cargo?'),
(UUID(), '¿Cómo considera que es la relación que tiene con su jefe inmediato?'),
(UUID(), '¿Cuál es la relación que tiene con el personal a su cargo?'),
(UUID(), '¿Cuál es el mayor reto que se ha encontrado en los trabajos que ha tenido y cómo lo ha resuelto?'),
(UUID(), '¿La empresa en la que trabaja está enterada de sus intereses académicos?'),
(UUID(), '¿Cuál ha sido la reacción de la empresa ante estos intereses?'),
(UUID(), '¿Considera combinar sus actividades profesionales con las académicas?');
