INSERT INTO preguntasFormatoEntrevista (nombrePreguntaFormatoEntrevista,tipoPregunta,seccion) VALUES 
('Fecha','date','Datos personales'),
('Nombre','text','Datos personales'),
('Apellido Paterno','text','Datos personales'),
('Apellido Materno','text','Datos personales'),
('Fecha de Nacimiento','date','Datos personales'),
('Edad','number','Datos personales'),
('Género','text','Datos personales'),
('Estado Civil','text','Datos personales'),
('Nacionalidad','text','Datos personales'),
('Estado de origen','text','Datos personales'),
('Dirección Actual','text','Datos personales'),
('Teléfono Fijo','tel','Datos personales'),
('Celular','tel','Datos personales'),
('Correo','email','Datos personales'),
('Realice una descripción amplia de su persona','textarea','Datos personales'),
('Describa su estado de ánimo cotidiano','textarea','Datos personales'),
('Describa su estado de ánimo en situaciones de presión','textarea','Datos personales'),
('Describa su estado de ánimo en situaciones críticas','textarea','Datos personales'),
('¿Cómo considera que es su estado de salud?','textarea','Datos personales'),
('¿A qué dedica sus tiempos libres?','textarea','Datos personales'),
('Nombre de la Licenciatura','text','Datos academicos'),
('Institución de Procedencia','text','Datos academicos'),
('Promedio de egreso','number','Datos academicos'),
('Generación (año)','number','Datos academicos'),
('Grado máximo de estudios','text','Datos academicos'),
('Maestría o especialidad (en caso de tener)','text','Datos academicos'),
('Institución donde curso la Maestría','text','Datos academicos'),
('Promedio de egreso de la Maestría','number','Datos academicos'),
('Cursos y Diplomados (Escribir los de los últimos tres años)','textarea','Datos academicos'),
('Idiomas que domina','textarea','Datos academicos'),
('¿Cómo considera que ha sido su desempeño académico hasta llegar a este posgrado?','textarea','Datos academicos'),
('¿Cuáles han sido los cursos de actualización, los seminarios o congresos a los que ha asistido que le han brindado mayores herramientas en su desarrollo profesional o personal?','textarea','Datos academicos'),
('¿Cómo surge el interés en este programa de posgrado?','textarea','Datos academicos'),
('¿Cuál es la finalidad de estudiar este posgrado y cómo se integrará en sus experiencias personales y/o profesionales?','textarea','Datos academicos'),
('¿Cuáles son sus expectativas acerca de las aportaciones que le pueda hacer este posgrado?','textarea','Datos academicos'),
('Explique su visión respecto a su desarrollo profesional en años posteriores a su egreso de este posgrado','textarea','Datos academicos'),
('¿Está dispuesto a cambiar de residencia?','textarea','Datos academicos'),
('Escribe el último trabajo en el que te desempeñaste','text','Datos laborales'),
('Lugar donde trabaja','text','Datos laborales'),
('Nombre de la empresa','text','Datos laborales'),
('Puesto que desempeña','text','Datos laborales'),
('Años en la empresa','number','Datos laborales'),
('Actividades que realiza','textarea','Datos laborales'),
('Sueldo que percibe','number','Datos laborales'),
('Tiene personal a su cargo','text','Datos laborales'),
('¿Cómo considera que es la relación que tiene con su jefe inmediato?','textarea','Datos laborales'),
('¿Cuál es la relación que tiene con el personal a su cargo?','textarea','Datos laborales'),
('¿Cuál es el mayor reto que se ha encontrado en los trabajos que ha tenido y como lo ha resuelto?','textarea','Datos laborales'),
('¿La empresa en la que trabaja está enterada de sus intereses académicos?','textarea','Datos laborales'),
('¿Cuál ha sido la reacción de la empresa ante estos intereses?','textarea','Datos laborales'),
('¿Considera combinar sus actividades profesionales con las académicas?','textarea','Datos laborales');
