INSERT INTO Paises (Id_pais, Nombre_pais) VALUES
(UUID(), 'Argentina'),
(UUID(), 'Brasil'),
(UUID(), 'Canadá'),
(UUID(), 'Chile'),
(UUID(), 'China'),
(UUID(), 'Colombia'),
(UUID(), 'Egipto'),
(UUID(), 'España'),
(UUID(), 'Estados Unidos'),
(UUID(), 'Francia'),
(UUID(), 'Alemania'),
(UUID(), 'India'),
(UUID(), 'Italia'),
(UUID(), 'Japón'),
(UUID(), 'México'),
(UUID(), 'Países Bajos'),
(UUID(), 'Perú'),
(UUID(), 'Reino Unido'),
(UUID(), 'Rusia'),
(UUID(), 'Sudáfrica');