INSERT INTO datosPersonales (idDatosPersonales, idGrupo, idPrueba, idAspirante, nombre, apellidoPaterno, apellidoMaterno, puestoSolicitado, fecha)
VALUES
-- Grupo G1_ISC - OTIS
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'juanlópez39@example.com')),
    'Juan', 'López', 'García', 'Analista de Datos', CURDATE()),

    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    5,
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'maríapérez76@example.com')), 
    'María', 'Pérez', 'Martínez', 'Desarrollador Web', CURDATE()),

    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    5,
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'carlosrodríguez58@example.com')),
    'Carlos', 'Rodríguez', 'Fernández', 'Investigador en IA', CURDATE()),

    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'lauragómez50@example.com')),
    'Laura', 'Gómez', 'Hernández', 'Psicóloga Organizacional', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'pedrofernández59@example.com')),
    'Pedro', 'Fernández', 'Ramírez', 'Ingeniero de Software', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'anamartínez97@example.com')),
    'Ana', 'Martínez', 'López', 'Diseñador UX/UI', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'luisramírez75@example.com')),
    'Luis', 'Ramírez', 'González', 'Científico de Datos', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'sofíaramírez88@example.com')),
    'Sofía', 'Ramírez', 'Torres', 'Consultor de RRHH', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'miguelramírez66@example.com')),
    'Miguel', 'Ramírez', 'Salinas', 'Administrador de Redes', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'elenagarcía10@example.com')),
    'Elena', 'García', 'Méndez', 'Analista de Mercado', CURDATE()),

-- Grupo G1_ISC - COLORES
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'juanlópez39@example.com')),
    'Juan', 'López', 'García', 'Analista de Sistemas', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'carlosrodríguez58@example.com')),
    'Carlos', 'Rodríguez', 'Fernández', 'Ingeniero de Software', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'pedrofernández59@example.com')),
    'Pedro', 'Fernández', 'Ramírez', 'Desarrollador Full Stack', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'luisramírez75@example.com')),
    'Luis', 'Ramírez', 'González', 'Especialista en Base de Datos', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'miguelramírez66@example.com')),
    'Miguel', 'Ramírez', 'Salinas', 'Desarrollador Backend', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'maríapérez76@example.com')),
    'María', 'Pérez', 'Martínez', 'Analista de QA', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'lauragómez50@example.com')),
    'Laura', 'Gómez', 'Hernández', 'Desarrolladora Frontend', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'anamartínez97@example.com')),
    'Ana', 'Martínez', 'López', 'Ingeniera DevOps', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'sofíaramírez88@example.com')),
    'Sofía', 'Ramírez', 'Torres', 'Analista de Seguridad', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G1_ISC'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'elenagarcía10@example.com')),
    'Elena', 'García', 'Méndez', 'Especialista UX', CURDATE()),

-- Grupo G2_II - OTIS
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'javierfernández98@example.com')),
    'Javier', 'Fernández', 'Torres', 'Ingeniero Industrial', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'fernandotorres81@example.com')),
    'Fernando', 'Torres', 'Vázquez', 'Investigador de Procesos', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'ricardogarcía68@example.com')),
    'Ricardo', 'García', 'Morales', 'Ingeniero Mecánico', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'manuelramírez62@example.com')),
    'Manuel', 'Ramírez', 'Suárez', 'Ingeniero de Planta', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'raúlgarcía25@example.com')),
    'Raúl', 'García', 'Díaz', 'Especialista en Calidad', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'lucíaramírez83@example.com')),
    'Lucía', 'Ramírez', 'Castro', 'Diseñadora Industrial', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'paulalópez49@example.com')),
    'Paula', 'López', 'Moreno', 'Ingeniera de Sistemas', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'gabrielagómez9@example.com')),
    'Gabriela', 'Gómez', 'Soto', 'Analista de Procesos', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'valeriagómez68@example.com')),
    'Valeria', 'Gómez', 'Bravo', 'Ingeniera Eléctrica', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    5, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'isabelfernández54@example.com')),
    'Isabel', 'Fernández', 'Reyes', 'Supervisora de Producción', CURDATE()),

-- Grupo G2_II - COLORES
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'javierfernández98@example.com')),
    'Javier', 'Fernández', 'Torres', 'Ingeniero de Producción', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'fernandotorres81@example.com')),
    'Fernando', 'Torres', 'Vázquez', 'Especialista en Logística', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'ricardogarcía68@example.com')),
    'Ricardo', 'García', 'Morales', 'Ingeniero de Materiales', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'manuelramírez62@example.com')),
    'Manuel', 'Ramírez', 'Suárez', 'Supervisor de Calidad', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'raúlgarcía25@example.com')),
    'Raúl', 'García', 'Díaz', 'Ingeniero de Mantenimiento', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'lucíaramírez83@example.com')),
    'Lucía', 'Ramírez', 'Castro', 'Ingeniera de Procesos', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'paulalópez49@example.com')),
    'Paula', 'López', 'Moreno', 'Analista de Proyectos', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'gabrielagómez9@example.com')),
    'Gabriela', 'Gómez', 'Soto', 'Ingeniera de Automatización', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'valeriagómez68@example.com')),
    'Valeria', 'Gómez', 'Bravo', 'Especialista en Manufactura', CURDATE()),
    
    (UUID(), 
    (SELECT idGrupo FROM grupos WHERE nombreGrupo = 'G2_II'), 
    6, 
    (SELECT idAspirante FROM aspirantes WHERE idUsuario = (SELECT idUsuario FROM usuarios WHERE correo = 'isabelfernández54@example.com')),
    'Isabel', 'Fernández', 'Reyes', 'Ingeniera de Control', CURDATE());